### PR TITLE
Date picker and Horizontal ScrollBar

### PR DESCRIPTION
**Pull request by Vivek-Kondpalle**
1) Date Picker in my Ordes page and Transactions page
2) Horizontal ScrollBar for childCategories in CategoryProducts

### CODE REVIEW

**Comment by ankitvat** [comment]
Please attach screenshots along with the PR

**Comment by Vivek-Kondpalle** [comment]
1) Date picker in Orders and transactions screen

Screenshot_2021-08-31-17-37-12-653_com go4lifeapp
Screenshot_2021-08-31-17-37-36-452_com go4lifeapp

2) Subscribe button not shown when not true and farmer image size increased.

Screenshot_2021-08-31-17-36-48-331_com go4lifeapp

**Comment by ankitvat** [comment]
Add the old date picker or enhance this one. Something which goes along the theme of the app.

**Comment by umakantv** [comment]
This one is fine. The old date picker is taking too much space.

**Comment by ankitvat** [comment]
Either add some icon or some border.This doesn't go along. Also change the font to the app's primary font.

**Pull request merged**
